name: Rai CICD Flow

on:
  push:
    branches:
      - master
      - feature/dockerise
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'oracle'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Login to Docker Hub
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $username -p $password

      - name: Build and Push Docker Image with Docker Compose
        run: |
          docker-compose build
          docker-compose push ${{ secrets.DOCKER_USERNAME }}/rai-workflow:latest